import time


#Request_ID ,前端发送来的请求规定

INTERFACEID_REG = 0
INTERFACEID_SEARCH = 1
INTERFACEID_DELETE = 2
INTERFACEID_EXIST = 3
INTERFACEID_COMPARE = 4
INTERFACEID_DETECT = 5
INTERFACEID_FEATURE = 6
INTERFACEID_GENDER = 7
INTERFACEID_AGE = 8
INTERFACEID_LIVE = 9
INTERFACEID_PERSON= 10
INTERFACEID_HAIR= 11
INTERFACEID_QUERY_REG = 12
INTERFACEID_DETECT_PROTOC = 13
INTERFACEID_MONITOR = 14
INTERFACEID_PERSIST_INDEX = 16
INTERFACEID_QUERY_SYSTEMINFO = 17
INTERFACEID_QUERY_VERIFIER_VER = 18
INTERFACEID_CROWDCNT = 19
INTERFACEID_QUALITY = 20
INTERFACEID_RACE = 21
INTERFACEID_CARD = 22
INTERFACEID_GLASS = 23
INTERFACEID_OLD_HELMET = 24
INTERFACEID_RUN = 25
INTERFACEID_GOGGLES = 26
INTERFACEID_CLOTHES = 27
INTERFACEID_THINGS = 28
INTERFACEID_PERSONATTR = 29
INTERFACEID_SMOKEFIRE = 30
INTERFACEID_REGIONINVADE = 31
INTERFACEID_CHANNELOCCUPY = 32
INTERFACEID_ITEMSTEAL = 33
INTERFACEID_ITEMSTRAND = 34

INTERFACEID_MASK = 36
INTERFACEID_HOVER = 37

INTERFACEID_GAS = 39
INTERFACEID_COUNT = 45



INTERFACEID_PEOPLESMOKE = 35
INTERFACEID_PEOPLEPHONE = 41
INTERFACEID_HELMET = 38
INTERFACEID_POSE = 40
INTERFACEID_COAL_1 = 42
INTERFACEID_COAL_2 = 43
INTERFACEID_DELETE_GENERAL=44


MAX_THREADS_PER_ALGORITHM = 10



#Method_ID，后端算法对应ID
PEOPLESMOKE_METHOD_ID=1
PEOPLEPHONE_METHOD_ID=2
HELMET_METHOD_ID=3
POSE_METHOD_ID=4
COAL_1_METHOD_ID=5
COAL_2_METHOD_ID=6
GENERALDETECT_METHOD_ID=7