class Error:
    FINDER_REG_SUCCESS = (0, "reg success")
    FINDER_REG_FAIL = (1, "reg fail")
    FINDER_SEARCH_SUCCESS = (0, "search success")
    FINDER_SEARCH_FAIL = (1, "search fail")
    FINDER_DELETE_SUCCESS = (0, "delete success")
    FINDER_DELETE_FAIL = (1, "delete fail")
    FINDER_EXIST_SUCCESS = (0, "exist success")
    FINDER_EXIST_FAIL = (1, "exist fail")
    FINDER_COMPARE_SUCCESS = (0, "compare success")
    FINDER_COMPARE_FAIL = (1, "compare fail")
    FINDER_DETECT_SUCCESS = (0, "detect success")
    FINDER_DETECT_FAIL = (1, "detect fail")
    FINDER_FEATURE_SUCCESS = (0, "feature success")
    FINDER_GENDER_SUCCESS = (0, "gender success")
    FINDER_AGE_SUCCESS = (0, "age success")
    FINDER_LIVE_SUCCESS = (0, "live success")
    FINDER_PERSON_SUCCESS = (0, "person success")
    FINDER_HAIR_SUCCESS = (0, "hair success")
    FINDER_QUERY_REG_SUCCESS = (0, "query reg_success")
    FAISS_INDEX_PERSIST_SUCCESS = (0, "persist faiss index success")
    FINDER_QUERY_SYSTEMINFO_SUCCESS = (0, "query system info success")
    FINDER_FETCH_VERIFIER_VERSION_SUCCESS = (0, "fetch verifier version success")
    FINDER_CROWDCNT_SUCCESS = (0, "crowd count success")
    FINDER_HELMET_DETECT_SUCCESS = (0, "helmet detect success")
    FINDER_RUNNER_DETECT_SUCCESS = (0, "runner detect success")
    FINDER_SMOKEFIRE_DETECT_SUCCESS = (0, "smoke fire detect success")
    FINDER_REGIONINVADE_DETECT_SUCCESS = (0, "region invade detect success")
    FINDER_HOVER_DETECT_SUCCESS = (0, "hover detect success")


    FINDER_CHANNELOCCUPY_DETECT_SUCCESS = (0, "channel occupy detect success")
    FINDER_ITEMSTEAL_DETECT_SUCCESS = (0, "item steal detect success")
    FINDER_ITEAMSTRAND_DETECT_SUCCESS = (0, "item strand detect success")
    FINDER_CARCARD_DETECT_SUCCESS = (0, "car card detect success")
    FINDER_MASKGLASSES_DETECT_SUCCESS = (0, "mask glasses detect success")
    FINDER_MASK_DETECT_SUCCESS = (0, "mask  detect success")
    FINDER_CLOTHES_DETECT_SUCCESS = (0, "clothes predict success")
    FINDER_THINGS_DETECT_SUCCESS = (0, "things detect success")
    FINDER_RACEPREDICT_SUCCESS = (0, "race predict success")
    FINDER_PERSONATTR_SUCCESS = (0, "face_attr success")

    FINDER_GAS_DETECT_SUCCESS = (0, "gas detect success")
    FINDER_GOGGLES_DETECT_SUCCESS = (0, "googles detect success")

    #complete interface
    FINDER_GENERAL_DETECT_SUCCESS = (0,"general detect success")
    FINDER_POSE_DETECT_SUCCESS = (0, "pose detect success")

    #plan to complete interface
    FINDER_PEOPLESMOKE_CLASSIFY_SUCCESS = (0, "people smoke classify success")
    FINDER_PEOPLEPHONE_CLASSIFY_SUCCESS = (0, "people phone classify success")
    FINDER_SMOKEPHONE_CLASSIFY_SUCCESS = (0, "people smoke&phone classify success")
    FINDER_TRACKCOAL_SUCCESS = (0, "track coal detect success")




    FINDER_API_KEY_INVALID  = (20001, "api key_invalid")
    FINDER_NONE_FACE  = (20002, "none face")
    FINDER_MULTI_FACE  = (20003, "multi face")
    FINDER_UNKNOW_ERROR = (20004, "unknow error")
    FINDER_PARAMETERS_ERROR  = (20005, "parameters error")
    ERROR_JSON_SYNTAX  = (20006, "error json_syntax")
    ERROR_IMAGE_BASE64  = (20007, "error image_base64")
    REQUEST_LIMITED  = (20008, "request limited")
    FINDER_PARAMETERS_EMPTY = (20009, "parameters empty")
    FINDER_NOT_AUTHORIZED  = (20010, "not authorized")
    FINDER_NOT_INTERFACE_ID  = (20011, "interface id not exist")
    FINDER_IMG_NUM_ERROR = (20012,"the number of img error")
